### PR TITLE
Slight performance improvement by minor changes

### PR DESCRIPTION
**Pull request by lambdalisue**
### Before

CleanShot 2021-10-31 at 01 13 46

### After
CleanShot 2021-10-31 at 01 14 09

### CODE REVIEW

**Comment by Shougo** [comment]
Hm....  I have tested it and it brokes ddc.vim plugin.

**Comment by lambdalisue** [comment]
> Hm.... I have tested it and it brokes ddc.vim plugin.

It broke ddc.vim like...? Does ddc.vim access private APIs (APIs not in `mod.ts` are assumed as PRIVATE)

**Comment by Shougo** [comment]
ddc.vim registers plugin manually.  I think it does not work.

```vim
  call denops#plugin#register('ddc',
        \ denops#util#join_path(s:root_dir, 'denops', 'ddc', 'app.ts'),
        \ { 'mode': 'skip' })
```

**Comment by lambdalisue** [comment]
@Shougo Fixed and force pushed. Could you try again?

**Comment by lambdalisue** [comment]
@Shougo Fixed (and force pushed). Could you try again?

**Comment by Shougo** [comment]
OH, it works.

**Review by Shougo — APPROVED** [review]

**Pull request merged**
