### PR TITLE
Use String(err) instead

### PR DESCRIPTION
**Pull request by Shougo**
Test.

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced error handling logic for clearer and more contextual error messages.
	- Improved formatting of error messages based on error types for better clarity.
	- Updated test cases to ensure consistent formatting of error messages.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Could you explain an example error message that shows stacktrace?

**Comment by Shougo** [comment]
Before:

```
"Failed to call 'not_exist_method' API in 'dummy': TypeError: this[#denops].dispatcher[fn] is not a function"
```

After:

```
"Failed to call 'not_exist_method' API in 'dummy': TypeError: this[#denops].dispatcher[fn] is not a function\n" +
"    at Plugin.call (file:///home/shougo/work/denops.vim/denops/@denops-private/service.ts:276:47)\n" +
"    at Service.#dispatch (file:///home/shougo/work/denops.vim/denops/@denops-private/service.ts:117:25)\n" +
"    at Service.dispatchAsync (file:///home/shougo/work/denops.vim/denops/@denops-private/service.ts:141:37)\n" +
"    at invoke (file:///home/shougo/work/denops.vim/denops/@denops-private/host.ts:92:22)\n" +
"    at Object.invoke (file:///home/shougo/work/denops.vim/denops/@denops-private/host/nvim.ts:34:16)\n" +
"    at dispatch (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/dispatcher.ts:36:36)\n" +
"    at Session.#dispatch (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:255:28)\n" +
"    at Session.#handleNotificationMessage (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:310:45)\n" +
"    at Session.#handleMessage (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:272:42)\n" +
"    at Object.write (https://jsr.io/@lambdalisue/messagepack-rpc/2.4.0/session.ts:165:63)",
```

**Comment by lambdalisue** [comment]
If that stack trace is all you have, it only points to the error within Denops itself and does not include the essential information about the error location in the Denops plugin. Do you have an example where the Denops plugin itself is throwing an error?

**Comment by Shougo** [comment]
For example this.

```
    async loadConfig(arg1: unknown): Promise<void> {
      await lock.lock(async () => {
        const path = ensure(arg1, is.String) as string;
        try {
          // NOTE: Import module with fragment so that reload works properly.
          // https://github.com/vim-denops/denops.vim/issues/227
          const mod = await import(
            `${toFileUrl(path).href}#${performance.now()}`
          );
          const obj = new mod.Config();
          await obj.config({ denops, contextBuilder, setAlias });
        } catch (e) {
          if (isDenoCacheIssueError(e)) {
            console.warn("*".repeat(80));
            console.warn(`Deno module cache issue is detected.`);
            console.warn(
              `Execute '!deno cache --reload "${path}"' and restart Vim/Neovim.`,
            );
            console.warn("*".repeat(80));
          }

          console.error(`Failed to load file '${path}': ${e}`);
          throw e;
        }
      });
      return Promise.resolve();
    },
```

**Comment by lambdalisue** [comment]
I mean the error message difference itself.

**Comment by Shougo** [comment]
For example this.

```
    async loadConfig(arg1: unknown): Promise<void> {
      await lock.lock(async () => {
        const path = ensure(arg1, is.String) as string;
        try {
          // NOTE: Import module with fragment so that reload works properly.
          // https://github.com/vim-denops/denops.vim/issues/227
          const mod = await import(
            `${toFileUrl(path).href}#${performance.now()}`
          );
          const obj = new mod.Config();
          await obj.config({ denops, contextBuilder, setAlias });
        } catch (e) {
          if (isDenoCacheIssueError(e)) {
            console.warn("*".repeat(80));
            console.warn(`Deno module cache issue is detected.`);
            console.warn(
              `Execute '!deno cache --reload "${path}"' and restart Vim/Neovim.`,
            );
            console.warn("*".repeat(80));
          }

          console.error(`Failed to load file '${path}': ${e}`);
          throw e;
        }
      });
      return Promise.resolve();
    },
```

**Pull request closed without merging**
