### PR TITLE
:boom: Drop support for previous versions of Deno/Vim/Neovim

### PR DESCRIPTION
**Pull request by lambdalisue**
We would like to remove support for older versions of Deno/Vim/Neovim from denops.vim and only support the current latest versions. This may be too aggressive, so please comment if you have any suggestions.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Some say that the homebrew version of Vim is a bit old and that it is better to follow the homebrew version. Therefore, the support policy is changed as follows.

1. support the two latest minor versions of Deno and Neovim because they support semantic version up.
2. the latest version of Vim is supported by homebrew.
    - Linux users usually build Vim themselves so never mind
    - Windows users can download the latest Vim from https://github.com/vim/vim-win32-installer so never mind
    - macOS users usually installe Vim with homebrew so follow homebrew

**Comment by lambdalisue** [comment]
I'd like to wait #206 because that may require the latest Neovim or require aggressive refactoring on `denops#server` module.

**Comment by lambdalisue** [comment]
I did refactoring on #214 so this PR would be merged soon

**Comment by 4513ECHO** [comment]
I think requirement of deno should be [v1.27.1](https://github.com/denoland/deno/releases/tag/v1.27.1) or later.
The autodiscovery of lockfile and the `--no-lock` flag was added in that version. Lockfile is useless a bit for denops.vim.
I think `--no-lock` flag should be added to `g:denops#server#deno_args` and `--no-check` flag should be removed because that has no effect now.
Then these changes should be followed up for [denops-shared-server.vim](https://github.com/vim-denops/denops-shared-server.vim).

**Pull request merged**
