### PR TITLE
:sparkles: Support a Shared server to avoid the bottleneck of process launches

### PR DESCRIPTION
**Pull request by lambdalisue**
# Usage

Start denops global server as follow

```
deno run -A --no-check ./denops/@denops-private/cli.ts
```

Then specify the address to `g:denops_server_addr` prior to Vim startup like

```vim
let g:denops_server_addr = '127.0.0.1:32123'
```

# Difference

Thanks to @ippachi at vim-jp slack.

##### Before

https://user-images.githubusercontent.com/546312/172044580-7e2419e7-48f5-419b-b098-35e22bf36208.mov

##### After

https://user-images.githubusercontent.com/546312/172044587-cdb47636-beec-41cf-a46f-4c6de81cca40.mov

### CODE REVIEW

**Comment by lambdalisue** [comment]
It seems Denops itself had some resource leak and this global denops emphasize that issue.

**Comment by lambdalisue** [comment]
Probably I'll merge it after 2022/06/10. Let me know if there are some issue on this PR.

**Comment by sigmaSd** [comment]
What about using std tee instead of the custom one? https://deno.land/std@0.133.0/async/tee.ts#L78

**Comment by Shougo** [comment]
Hi, the `bin/denops` works.

```sh
#!/usr/bin/bash
cd "$(dirname "$(readlink -f "$0")")"
deno run -A --no-check ../denops/@denops-private/cli.ts
```

Can you include it?

**Comment by lambdalisue** [comment]
> What about using std tee instead of the custom one? https://deno.land/std@0.133.0/async/tee.ts#L78

Unfortunately, that's for `AsyncIterator` but what we need is tee for `Deno.Reader`. We can convert `Deno.Reader` to `AsyncIterator` but it would add some extra cost.

> Can you include it?

Unfortunately no. 

1. It does not support Windows
2. `readlink` is not common enough (some unix OS does not provide it in default)
3. We don't want to maintain multiple script just for that

**Pull request merged**
